# -*- coding: utf-8 -*-
"""
Unit test module for psa_lgu_comparison_panel.py (gmd_scripts/psa_lgu_comparison_panel.py).
Auto-generated by scripts/testing/generate_test_stubs.py
"""

import unittest
import importlib
from tests.mocks.qgis_mock import setup_qgis_mock_if_needed, QgsProcessingContext
from tests.mocks.sample_data import create_sample_polygon_layer, create_sample_point_layer

setup_qgis_mock_if_needed()

try:
    from qgis.core import QgsVectorLayer, QgsFields, QgsField
    from qgis.PyQt.QtCore import QVariant
except ImportError:
    from tests.mocks.qgis_mock import QgsVectorLayer, QgsFields, QgsField, MockQVariant as QVariant


class TestPsaLguComparisonPanel(unittest.TestCase):
    """Test suite for psa_lgu_comparison_panel.py."""

    def setUp(self):
        self.mod = importlib.import_module("gmd_scripts.psa_lgu_comparison_panel")
        self.sample_polygon = create_sample_polygon_layer("Sample_Polygon_Layer", count=3)
        self.sample_point = create_sample_point_layer("Sample_Point_Layer", count=5)

    def test_module_import(self):
        """Verify that the module imports successfully without syntax or module errors."""
        self.assertIsNotNone(self.mod, "Module gmd_scripts.psa_lgu_comparison_panel should import successfully.")

    def test_sample_data_layer_processing(self):
        """Test module functionality using sample vector layer fixtures."""
        self.assertTrue(self.sample_polygon.isValid(), "Sample polygon layer should be valid.")
        self.assertGreaterEqual(self.sample_polygon.featureCount(), 3)


def _layer_with_fields(name, field_specs):
    """Build a memory layer named *name* with fields from
    field_specs = [(field_name, QVariant type), ...] and no features."""
    fields = QgsFields()
    for fname, ftype in field_specs:
        fields.append(QgsField(fname, ftype))
    layer = QgsVectorLayer("Polygon?crs=EPSG:4326", name, "memory")
    layer.dataProvider().addAttributes(fields)
    layer.updateFields()
    return layer


class TestGeocodeFieldResolution(unittest.TestCase):
    """Regression tests for the bug where the review panel's barangay
    dropdown could show the wrong geocode in its label.

    Root cause: the algorithm appends the matched barangay's first8-
    truncated geocode under the name "geocode", but PSA/LGU source layers
    routinely already carry their OWN "geocode" field (that's exactly what
    Geocode Field auto-detection looks for), so the appended column
    silently lands under a different name ("geocode_2", ...) to avoid a
    collision. The panel was doing a blind case-insensitive "geocode" name
    search, which -- whenever that collision happened -- kept finding the
    ORIGINAL, untruncated source field instead of the correct one.

    _geocode_field() fixes this by preferring the GEOCODE_FIELD_PROPERTY
    tag the algorithm now stamps onto its Matched PSA/LGU outputs, which
    names the exact resolved field regardless of collision."""

    def setUp(self):
        self.mod = importlib.import_module("gmd_scripts.psa_lgu_comparison_panel")

    def test_prefers_tagged_property_over_colliding_original_field(self):
        """The regression case itself: both the stale original "geocode"
        field and the algorithm's correctly-tagged "geocode_2" are present
        -- the tag must win."""
        layer = _layer_with_fields("PSA_Matched", [
            ("geocode", QVariant.String),
            ("geocode_2", QVariant.String),
        ])
        layer.setCustomProperty(self.mod.GEOCODE_FIELD_PROPERTY, "geocode_2")
        self.assertEqual(self.mod._geocode_field(layer), "geocode_2")

    def test_falls_back_to_plain_name_when_untagged(self):
        """A layer with no tag at all -- e.g. ref_mbi_cases, which is never
        one of this algorithm's own outputs -- still resolves via a plain
        "geocode" name search, same as before this fix."""
        layer = _layer_with_fields("ref_mbi_cases", [("geocode", QVariant.String)])
        self.assertEqual(self.mod._geocode_field(layer), "geocode")

    def test_ignores_stale_tag_naming_a_field_that_does_not_exist(self):
        """A tag pointing at a field the layer doesn't actually have (e.g.
        left over some other way) falls back to the plain search rather
        than returning nothing."""
        layer = _layer_with_fields("PSA_Matched", [("geocode", QVariant.String)])
        layer.setCustomProperty(self.mod.GEOCODE_FIELD_PROPERTY, "geocode_2")
        self.assertEqual(self.mod._geocode_field(layer), "geocode")

    def test_returns_none_without_any_geocode_field(self):
        layer = _layer_with_fields("Other", [("name", QVariant.String)])
        self.assertIsNone(self.mod._geocode_field(layer))


if __name__ == "__main__":
    unittest.main()
