# -*- coding: utf-8 -*-
"""
Unit test module for package_layers_by_citymun.py (gmd_scripts/package_layers_by_citymun.py).
Auto-generated by scripts/testing/generate_test_stubs.py
"""

import unittest
import importlib
from tests.mocks.qgis_mock import setup_qgis_mock_if_needed, QgsProcessingContext
from tests.mocks.sample_data import create_sample_polygon_layer, create_sample_point_layer

setup_qgis_mock_if_needed()


class TestPackageLayersByCitymun(unittest.TestCase):
    """Test suite for package_layers_by_citymun.py."""

    def setUp(self):
        self.mod = importlib.import_module("gmd_scripts.package_layers_by_citymun")
        self.sample_polygon = create_sample_polygon_layer("Sample_Polygon_Layer", count=3)
        self.sample_point = create_sample_point_layer("Sample_Point_Layer", count=5)

    def test_module_import(self):
        """Verify that the module imports successfully without syntax or module errors."""
        self.assertIsNotNone(self.mod, "Module gmd_scripts.package_layers_by_citymun should import successfully.")

    def test_sample_data_layer_processing(self):
        """Test module functionality using sample vector layer fixtures."""
        self.assertTrue(self.sample_polygon.isValid(), "Sample polygon layer should be valid.")
        self.assertGreaterEqual(self.sample_polygon.featureCount(), 3)


if __name__ == "__main__":
    unittest.main()
