# -*- coding: utf-8 -*-
"""
Automated Unit Test Generator for GEMMA QGIS Plugin scripts.
Scans gmd_scripts/ and generates test stubs in tests/unit/ for any script missing coverage.

Usage:
  python scripts/testing/generate_test_stubs.py          # Auto-creates missing test stubs
  python scripts/testing/generate_test_stubs.py --check  # Fails if any script is missing a unit test file
"""

import sys
import os
import re
import argparse
import unittest
from pathlib import Path

# Set up project root in python path
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from tests.mocks.qgis_mock import setup_qgis_mock_if_needed
setup_qgis_mock_if_needed()

TEST_TEMPLATE = '''# -*- coding: utf-8 -*-
"""
Unit test module for {module_name} ({rel_path}).
Auto-generated by scripts/testing/generate_test_stubs.py
"""

import unittest
import importlib
from tests.mocks.qgis_mock import setup_qgis_mock_if_needed, QgsProcessingContext
from tests.mocks.sample_data import create_sample_polygon_layer, create_sample_point_layer

setup_qgis_mock_if_needed()


class Test{class_name}(unittest.TestCase):
    """Test suite for {module_name}."""

    def setUp(self):
        self.mod = importlib.import_module("{import_path}")
        self.sample_polygon = create_sample_polygon_layer("Sample_Polygon_Layer", count=3)
        self.sample_point = create_sample_point_layer("Sample_Point_Layer", count=5)

    def test_module_import(self):
        """Verify that the module imports successfully without syntax or module errors."""
        self.assertIsNotNone(self.mod, "Module {import_path} should import successfully.")

    def test_sample_data_layer_processing(self):
        """Test module functionality using sample vector layer fixtures."""
        self.assertTrue(self.sample_polygon.isValid(), "Sample polygon layer should be valid.")
        self.assertGreaterEqual(self.sample_polygon.featureCount(), 3)


if __name__ == "__main__":
    unittest.main()
'''


def get_target_scripts():
    """Find python scripts in gmd_scripts/ that should have unit tests."""
    gmd_dir = PROJECT_ROOT / "gmd_scripts"
    scripts = []

    if not gmd_dir.exists():
        return scripts

    for file_path in gmd_dir.rglob("*.py"):
        # Ignore __init__.py, deprecated subdirectories, and cbms_mv module
        if (
            file_path.name == "__init__.py"
            or "deprecated" in file_path.parts
            or "cbms_mv" in file_path.parts
        ):
            continue
        scripts.append(file_path)

    return sorted(scripts)


def to_snake_case_name(file_path):
    """Convert filename to test file name e.g. gmdhelpers.py -> test_gmdhelpers.py."""
    stem = file_path.stem
    if stem.startswith("test_"):
        return f"{stem}.py"
    return f"test_{stem}.py"


def to_class_name(stem):
    """Convert file stem to CamelCase class name."""
    clean = stem.replace("test_", "")
    parts = clean.split("_")
    return "".join(p.capitalize() for p in parts if p)


def sync_skill_docs():
    """Update SKILL.md test counts and architecture tree automatically."""
    skill_file = PROJECT_ROOT / ".agents" / "skills" / "qgis-test-pipeline" / "SKILL.md"
    if not skill_file.exists():
        return

    unit_dir = PROJECT_ROOT / "tests" / "unit"
    loader = unittest.TestLoader()

    module_counts = {}
    for py_file in sorted(unit_dir.glob("test_*.py")):
        mod_name = py_file.stem
        try:
            suite = loader.loadTestsFromName(f"tests.unit.{mod_name}")
            module_counts[mod_name] = suite.countTestCases()
        except Exception:
            module_counts[mod_name] = 1

    total_tests = sum(module_counts.values())
    total_modules = len(module_counts)

    content = skill_file.read_text(encoding="utf-8")

    # Update totals line
    totals_pattern = r"\*\*Current Suite Totals\*\*:\s*\*\*\d+\s*tests\*\*\s*across\s*\*\*\d+\s*test modules\*\*"
    new_totals = f"**Current Suite Totals**: **{total_tests} tests** across **{total_modules} test modules**"
    content = re.sub(totals_pattern, new_totals, content)

    # Update test breakdown in tree
    tree_lines = []
    descriptions = {
        "test_apply_qml_styles": "QML style application",
        "test_auto_arrange": "Auto-arrange layer ordering",
        "test_check_and_update_dialog": "Check & update dialog",
        "test_clip_project_layers": "Layer clipping",
        "test_create_enumeration_area": "EA creation",
        "test_ea_merge_processor": "EA merge processor",
        "test_ea_pipeline": "Full EA delineation pipeline",
        "test_ea_split_modes": "EA split mode strategies",
        "test_export_preliminary_polygons": "Preliminary polygon export",
        "test_fill_polygon_gaps": "Gap filling",
        "test_gaps_overlaps_checker": "Gap & overlap detection",
        "test_geom_check_repair_legacy": "Legacy geometry repair",
        "test_geom_repair_toolkit": "Topology engine & repair toolkit",
        "test_gmdhelpers": "Core helper functions",
        "test_gsheet": "Google Sheets integration",
        "test_join_barangay_attributes": "Barangay attribute joining",
        "test_lgu_fix_processing": "LGU fix processing",
        "test_mbi_run_analysis": "Run Analysis MBI reference cases engine",
        "test_mbi_validator": "MBI validation engine",
        "test_package_qfield": "QField packaging",
        "test_pre_ea_processor": "Pre-EA processor",
        "test_repair_geometry_errors": "Geometry error repair",
        "test_scan_geometry_errors": "Geometry error scanning",
        "test_update_metadata": "Metadata update",
        "test_update_metadata_by_geocode": "Geocode metadata update",
    }

    for mod, count in sorted(module_counts.items()):
        desc = descriptions.get(mod, "Automated unit test module")
        unit_str = f"{count} test" if count == 1 else f"{count} tests"
        tree_lines.append(f"│   │   ├── {mod}.py".ljust(46) + f"# {unit_str} — {desc}")

    if tree_lines:
        tree_lines[-1] = tree_lines[-1].replace("├──", "└──")
        unit_tree_block = "\n".join(tree_lines)
        unit_block_pattern = r"(│\s*├── unit/\n)([\s\S]*?)(│\s*├── integration/)"
        content = re.sub(unit_block_pattern, rf"\g<1>{unit_tree_block}\n│   \g<3>", content)

    skill_file.write_text(content, encoding="utf-8")
    print(f"[INFO] Synced SKILL.md with {total_tests} tests across {total_modules} modules.")


def run_generator(check_only=False, sync_docs=True):
    target_scripts = get_target_scripts()
    unit_tests_dir = PROJECT_ROOT / "tests" / "unit"
    unit_tests_dir.mkdir(parents=True, exist_ok=True)

    missing_tests = []
    created_tests = []

    for script_path in target_scripts:
        test_filename = to_snake_case_name(script_path)
        test_path = unit_tests_dir / test_filename

        if not test_path.exists():
            missing_tests.append((script_path, test_path))
            if not check_only:
                # Generate test file
                rel_path = script_path.relative_to(PROJECT_ROOT).as_posix()
                rel_import = rel_path.replace(".py", "").replace("/", ".")
                class_name = to_class_name(script_path.stem)

                content = TEST_TEMPLATE.format(
                    module_name=script_path.name,
                    rel_path=rel_path,
                    import_path=rel_import,
                    class_name=class_name
                )

                test_path.write_text(content, encoding="utf-8")
                created_tests.append(test_path)

    if check_only:
        if missing_tests:
            print(f"[CHECK FAILED] {len(missing_tests)} script(s) are missing unit test files in tests/unit/:")
            for script_path, test_path in missing_tests:
                print(f"  - Script: {script_path.relative_to(PROJECT_ROOT)} (Expected test: {test_path.relative_to(PROJECT_ROOT)})")
            return False
        else:
            print("[CHECK PASSED] All scripts in gmd_scripts/ have corresponding unit test files.")
            return True

    print(f"[INFO] Scanned {len(target_scripts)} scripts in gmd_scripts/.")
    if created_tests:
        print(f"[SUCCESS] Generated {len(created_tests)} new unit test stub(s):")
        for tp in created_tests:
            print(f"  + {tp.relative_to(PROJECT_ROOT)}")
    else:
        print("[INFO] All scripts already have unit test files in tests/unit/.")

    if sync_docs:
        sync_skill_docs()

    return True


def main():
    parser = argparse.ArgumentParser(description="Auto-generate unit test stubs and sync test docs for GEMMA plugin scripts.")
    parser.add_argument("--check", action="store_true", help="Check if all scripts have unit tests without creating them.")
    parser.add_argument("--sync-skill", action="store_true", help="Sync SKILL.md test counts and architecture tree.")
    args = parser.parse_args()

    if args.sync_skill:
        sync_skill_docs()
        return

    success = run_generator(check_only=args.check)
    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
